#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"

task main () {
	int normalPower = 40;
	int fasterPower = 60;
	int sonarThreshHold = 10;
  int _dir = 0;
	int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;

  nxtDisplayCenteredTextLine(0, "IR Beacon Follower");
  nxtDisplayCenteredTextLine(1, "Attatch these:");
  nxtDisplayCenteredTextLine(2, "Sonar => S2");
  nxtDisplayCenteredTextLine(3, "IR => S3");
  nxtDisplayCenteredTextLine(4, "Program needs testing");
  nxtDisplayCenteredTextLine(5, "and adjusting. Config");
  nxtDisplayCenteredTextLine(6, "at 10, 11, and 12");
  wait1Msec(4000);

  while(true) {
    eraseDisplay();

    // read all of the sensors' values at once,
    // exit the app if an error occurs
    if (!HTIRS2readAllDCStrength(HTIRS2, dcS1, dcS2, dcS3, dcS4, dcS5)) {
      nxtDisplayTextLine(4, "ERROR!!");
      wait1Msec(2000);
      StopAllTasks();
    }

    // read the direction from which the signal is coming,
    // exit the app if an error occurs
    _dir = HTIRS2readDCDir(HTIRS2);
    if (_dir < 0) {
      nxtDisplayTextLine(4, "ERROR!!");
      wait1Msec(2000);
      StopAllTasks();
    }

    //adjust direction that is 1..9 to become -4..4
    int dir = _dir - 5;

    // display the info from the sensor
    nxtDisplayTextLine(0,"HT IR Seeker");
    nxtDisplayTextLine(2, "dir: %2d", dir);
    nxtDisplayTextLine(3, "S1: %3d", dcS1);
    nxtDisplayTextLine(4, "S2: %3d", dcS2);
    nxtDisplayTextLine(5, "S3: %3d", dcS3);
    nxtDisplayTextLine(6, "S4: %3d", dcS4);
    nxtDisplayTextLine(7, "S5: %3d", dcS5);
    //dir should be a number between -4 and 4
    //If it is -1 to -4, the robot is facing too far right
    //If it is 1 to 4, the robot is facing too far left
    //If it is 0, we're right on track :D

    //adjusts vars
    int lPow = normalPower;
    int rPow = normalPower;
    if (dir < 0)
    	lPow = fasterPower;
    if (dir > 0)
    	rPow = fasterPower;

    //set motor vars
    motor[motorL] = lPow;
    motor[motorR] = rPow;

    //test to see if we're knocking over the PVC
    if (SensorValue(sonar) < sonarThreshHold)
    	break;

    //wait a moment so that the program doesn't trip own itself
    wait10Msec(10);
  }
}
