#pragma config(Sensor, S4,     sound,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int getClaps()
{
	int claps = 0;
	int time = 700;
	int targetTime = time;
	ClearTimer(T1);
	while(time1[T1] < targetTime)
	{
		if (SensorValue[sound] > 60)
		{
			claps += 1;
			wait1Msec(100);
			targetTime = time + time1[T1];
		}
	}
	return claps;
}

int waitGetClaps()
{
	while(SensorValue[sound] < 60) { }
	int claps = getClaps();
	return claps + 1;
}

task main()
{
	int claps = waitGetClaps();
	nxtDisplayCenteredTextLine(3, "Claps: %d", claps);
}
