#pragma config(Sensor, S3,     colorPort,           sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	motor[motorB] = 50;
	motor[motorC] = 50;
	while (SensorValue[colorPort] != GREENCOLOR) {}
	motor[motorB] = 0;
	motor[motorC] = 0;
}
