#pragma config(StandardModel, "RANGER")
#pragma config(RenamedStdModelMotor, mtr_S1_C1_1, motorR)
#pragma config(RenamedStdModelMotor, mtr_S1_C1_2, motorL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
/*
typedef struct {
	int begin;
	int end;
	int power;
} range;

range lv1 = {2, 30, 15};
range lv2 = {31, 60, 45};
range lv3 = {61, 90, 75};
range lv4 = {91, 128, 115};
range lv1, lv2, lv3, lv4;*/
int ranges[4][3];
int rangeLength = 4;
int subRanges[4][3];
int subRangeLength = 4;
int mainRanges[4][3];
int mainRangeLength = rangeLength;

int getPow(int amt, int fast) {
	if (fast == 1) {
		mainRanges = ranges;
		mainRangeLength = rangeLength;
	} else {
		mainRanges = subRanges;
		mainRangeLength = subRangeLength;
	}
	int posAmt = amt;
	if (posAmt < 0) { posAmt *= -1; }
	for (int i = 0; i < mainRangeLength; i++) {
		if (posAmt >= mainRanges[i][0] && posAmt <= mainRanges[i][1]) {
			return (mainRanges[i][2]) * (amt / posAmt);
		}
	}
	return 0;
}

task main()
{
	ranges[0][0] = 5;   ranges[0][1] = 50;   ranges[0][2] = 15;
	ranges[1][0] = 51;  ranges[1][1] = 90;   ranges[1][2] = 45;
	ranges[2][0] = 91;  ranges[2][1] = 120;  ranges[2][2] = 75;
	ranges[3][0] = 121; ranges[3][1] = 128;  ranges[3][2] = 100;

	subRanges[0][0] = 5;   subRanges[0][1] = 50;   subRanges[0][2] = 5;
	subRanges[1][0] = 51;  subRanges[1][1] = 90;   subRanges[1][2] = 15;
	subRanges[2][0] = 91;  subRanges[2][1] = 120;  subRanges[2][2] = 25;
	subRanges[3][0] = 121; subRanges[3][1] = 128;  subRanges[3][2] = 35;
	//setup
	/*
	lv1.begin = 2;  lv1.end = 30;  lv1.power = 15;
	lv2.begin = 31; lv2.end = 60;  lv2.power = 45;
	lv3.begin = 61; lv3.end = 90;  lv3.power = 75;
	lv4.begin = 91; lv4.end = 128; lv4.power = 115;

	ranges[0] = lv1;
	ranges[1] = lv2;
	ranges[2] = lv3;
	ranges[3] = lv4;*/
	bool fast = true;
	bool notPressed = true;
  while(true)
  {
  	if (joy1Btn(1) == 1 && notPressed) {
  		fast = !fast;
  		notPressed = false;
  	}
  	if (joy1Btn(1) == 0) {
  		notPressed = true;
  	}
    getJoystickSettings(joystick);
    int left = joystick.joy1_y1;
    int right = joystick.joy1_y2;
    int leftPower = getPow(left, fast);
    int rightPower = getPow(right, fast);
    nxtDisplayTextLine(0, "Left: %d, Right: %d", left, right);
    nxtDisplayTextLine(1, "Left: %d, Right: %d", leftPower, rightPower);
    nxtDisplayTextLine(2, "Fast: %d", fast);
    motor[motorL] = left;
    motor[motorR] = right;
  }
  //joy1Btn(1) == 1 || joy1Btn(1) == 0
}
