#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     sound,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;
	while(true) {
		nxtDisplayTextLine(0, "S1: %d", SensorValue(sonar));
		nxtDisplayTextLine(1, "S2: %d", SensorValue(S2));
		nxtDisplayTextLine(2, "S3: %d", SensorValue(S3));
		nxtDisplayTextLine(3, "S4: %d", SensorValue(sound));
		nxtDisplayTextLine(4, "motorA: %d", nMotorEncoder[motorA]);
		nxtDisplayTextLine(5, "motorB: %d", nMotorEncoder[motorB]);
		nxtDisplayTextLine(6, "motorC: %d", nMotorEncoder[motorC]);
	}
}
